name: Test Curl

on:
  workflow_dispatch:

jobs:
  curl_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Test Curl 
      run: |
        curl 'https://example.com' \
          -H 'Accept: */*' \
          -H 'Accept-Language: en-US,en;q=0.9' \
          -H 'Cache-Control: no-cache' \
          -H 'Connection: keep-alive' \
          --compressed \
          --max-time 10 \
          --output file.txt
    - uses: deka0106/upload-to-dropbox@v2
      with:
        dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        src: file.txt
        dest: /GithubActionData/
        autorename: true
    
